import type { Metadata } from "next";
import Link from "next/link";
import type { CSSProperties } from "react";
import {
  DESIGNS,
  REFERENCES,
  type Design,
  type FontUse,
} from "../_lib/designs";
import {
  MODELS,
  VARIATIONS,
  type ModelKey,
  type Variation,
} from "../_lib/variations";
import { FONT_CLASS } from "./_components/fonts";

export const metadata: Metadata = {
  title: "Landing page variations | Heavenly Travel",
  description:
    "Six landing page concepts for Heavenly Travel, generated by Claude Opus 5 and Claude Fable 5.1, compared with the Codex concept and the current site.",
};

const GROUPS: ModelKey[] = ["opus", "fable"];

type Entry = {
  id: string;
  title: string;
  subtitle: string;
  href: string;
  external?: boolean;
  design: Design;
};

function shortName(v: Variation) {
  return `${v.model === "opus" ? "Opus" : "Fable"} ${v.option}`;
}

const OPTIONS: Entry[] = VARIATIONS.flatMap((v) => {
  const design = DESIGNS[v.href];
  return design
    ? [
        {
          id: v.href,
          title: shortName(v),
          subtitle: v.seed,
          href: v.href,
          design,
        },
      ]
    : [];
});

const REFS: Entry[] = REFERENCES.map((r) => ({
  id: r.href,
  title: r.name,
  subtitle: r.by,
  href: r.href,
  external: true,
  design: r.design,
}));

const ALL: Entry[] = [...OPTIONS, ...REFS];

function fontStyle(font: FontUse): CSSProperties | undefined {
  return font.key === "archivo" && font.family.includes("125")
    ? { fontVariationSettings: "'wdth' 125" }
    : undefined;
}

function EntryLink({
  entry,
  className,
  children,
}: {
  entry: Entry;
  className: string;
  children: React.ReactNode;
}) {
  return entry.external ? (
    <a
      href={entry.href}
      className={className}
      target="_blank"
      rel="noopener noreferrer"
    >
      {children}
    </a>
  ) : (
    <Link href={entry.href} className={className}>
      {children}
    </Link>
  );
}

const ROWS: { label: string; cell: (d: Design) => React.ReactNode }[] = [
  {
    label: "Palette",
    cell: (d) => (
      <div className="flex gap-1">
        {d.palette.map((s) => (
          <span
            key={s.hex}
            title={`${s.name} ${s.hex}`}
            className="h-5 w-5 rounded-sm ring-1 ring-black/10"
            style={{ backgroundColor: s.hex }}
          />
        ))}
      </div>
    ),
  },
  {
    label: "Display font",
    cell: (d) => (
      <span
        className={`${FONT_CLASS[d.display.key]} text-base`}
        style={fontStyle(d.display)}
      >
        {d.display.family}
      </span>
    ),
  },
  {
    label: "Body font",
    cell: (d) => (
      <span className={`${FONT_CLASS[d.body.key]} text-base`}>
        {d.body.family}
      </span>
    ),
  },
  { label: "Hero", cell: (d) => d.hero },
  { label: "Imagery", cell: (d) => d.imagery },
  { label: "Shape", cell: (d) => d.shape },
  { label: "Motion", cell: (d) => d.motion },
  { label: "Voice", cell: (d) => d.voice },
  {
    label: "Worth lifting",
    cell: (d) => <span className="font-medium">{d.lift}</span>,
  },
];

function Card({ entry }: { entry: Entry }) {
  const d = entry.design;
  return (
    <article className="rounded-2xl border border-neutral-200 p-5 sm:p-6">
      <div className="flex flex-wrap items-baseline justify-between gap-3">
        <h3 className="text-xl font-semibold">
          {entry.title} · {d.label}
        </h3>
        <EntryLink
          entry={entry}
          className="text-sm font-medium underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2"
        >
          {entry.external ? "Open site" : "Open page"}
        </EntryLink>
      </div>
      <p className="mt-1 text-sm text-neutral-500">{entry.subtitle}</p>

      <ul className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5">
        {d.palette.map((s) => (
          <li key={s.hex} className="text-xs">
            <div
              className="h-10 rounded-md ring-1 ring-black/10"
              style={{ backgroundColor: s.hex }}
            />
            <p className="mt-1.5 font-medium">{s.name}</p>
            <p className="font-mono text-neutral-500">{s.hex}</p>
            <p className="text-neutral-600">{s.role}</p>
          </li>
        ))}
      </ul>

      <div className="mt-5 rounded-lg bg-neutral-50 p-4">
        <p
          className={`${FONT_CLASS[d.display.key]} text-2xl leading-tight tracking-tight`}
          style={fontStyle(d.display)}
        >
          A better way to get away.
        </p>
        <p className="mt-1 text-xs text-neutral-500">
          {d.display.family}, {d.display.note}
        </p>
        <p className={`${FONT_CLASS[d.body.key]} mt-3 text-base`}>
          Coach charter and cars with driver, wherever you are in Malaysia.
        </p>
        <p className="mt-1 text-xs text-neutral-500">
          {d.body.family}, {d.body.note}
        </p>
      </div>

      <dl className="mt-5 grid gap-x-6 gap-y-3 text-sm sm:grid-cols-[6rem_1fr]">
        <dt className="text-neutral-500">Hero</dt>
        <dd>{d.hero}</dd>
        <dt className="text-neutral-500">Imagery</dt>
        <dd>{d.imagery}</dd>
        <dt className="text-neutral-500">Shape</dt>
        <dd>{d.shape}</dd>
        <dt className="text-neutral-500">Motion</dt>
        <dd>{d.motion}</dd>
        <dt className="text-neutral-500">Voice</dt>
        <dd>{d.voice}</dd>
        <dt className="text-neutral-500">Worth lifting</dt>
        <dd className="font-medium">{d.lift}</dd>
      </dl>
    </article>
  );
}

export default function LandingIndex() {
  return (
    <div className="min-h-screen bg-white font-sans text-neutral-900">
      <main className="mx-auto max-w-5xl px-5 pt-16 pb-32 sm:px-8">
        <div className="flex gap-4 text-sm text-neutral-500">
          <Link href="/" className="underline-offset-4 hover:underline">
            Home
          </Link>
          <Link href="/model" className="underline-offset-4 hover:underline">
            Model stats
          </Link>
        </div>
        <h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
          Landing page variations
        </h1>
        <p className="mt-3 max-w-2xl text-neutral-600">
          Three options per model from the same brief, alongside the Codex
          concept and the current WordPress site. The six options and the Codex
          concept share the same headline; what differs is below.
        </p>

        <div className="mt-10 overflow-x-auto rounded-xl border border-neutral-200">
          <table className="w-full min-w-[1180px] text-left text-sm">
            <caption className="sr-only">
              Design traits of the six options and two reference sites
            </caption>
            <thead className="bg-neutral-50 text-neutral-600">
              <tr>
                <th scope="col" className="w-28 px-4 py-3 font-medium">
                  Trait
                </th>
                {ALL.map((e) => (
                  <th
                    key={e.id}
                    scope="col"
                    className={`px-4 py-3 font-medium ${
                      e.external ? "border-l border-neutral-200" : ""
                    }`}
                  >
                    <EntryLink
                      entry={e}
                      className="text-neutral-900 underline-offset-4 hover:underline"
                    >
                      {e.title}
                    </EntryLink>
                    <span className="block text-xs font-normal">
                      {e.design.label}
                    </span>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-200 align-top">
              {ROWS.map((row) => (
                <tr key={row.label}>
                  <th
                    scope="row"
                    className="bg-neutral-50 px-4 py-3 font-medium text-neutral-600"
                  >
                    {row.label}
                  </th>
                  {ALL.map((e) => (
                    <td
                      key={e.id}
                      className={`px-4 py-3 text-neutral-700 ${
                        e.external ? "border-l border-neutral-200" : ""
                      }`}
                    >
                      {row.cell(e.design)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {GROUPS.map((model) => (
          <section key={model} className="mt-14">
            <h2 className="text-2xl font-semibold tracking-tight">
              {MODELS[model].name}
            </h2>
            <div className="mt-5 space-y-6">
              {OPTIONS.filter((e) =>
                e.href.startsWith(`/landing/${model}/`),
              ).map((e) => (
                <Card key={e.id} entry={e} />
              ))}
            </div>
          </section>
        ))}

        <section className="mt-14">
          <h2 className="text-2xl font-semibold tracking-tight">
            Reference sites
          </h2>
          <p className="mt-1 text-sm text-neutral-500">
            Not generated here; summarised from their live HTML and CSS for
            comparison.
          </p>
          <div className="mt-5 space-y-6">
            {REFS.map((e) => (
              <Card key={e.id} entry={e} />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
