import type { Metadata } from "next";
import Link from "next/link";
import { Chips } from "../_components/Chips";
import { DesignCard, DesignTable } from "../_components/DesignSummary";
import {
  IDEA_ENTRIES,
  REFERENCE_ENTRIES,
  VARIATION_ENTRIES,
} from "../_lib/designs";
import { IDEAS } from "../_lib/ideas";
import { REIMAGINED } from "../_lib/reimagined";
import { MODELS, type ModelKey } from "../_lib/variations";

export const metadata: Metadata = {
  title: "Landing page variations | Heavenly Travel",
  description:
    "Six landing page concepts for Heavenly Travel, generated by Claude Opus 5 and Claude Fable 5.1, compared with the Codex concept and the current site, plus four sites reimagined from reference platforms and four ideas that replace the platform layout altogether.",
};

const GROUPS: ModelKey[] = ["opus", "fable"];

const ALL = [...VARIATION_ENTRIES, ...REFERENCE_ENTRIES];

export default function LandingIndex() {
  return (
    <div className="min-h-screen bg-white font-sans text-neutral-900">
      <main className="mx-auto max-w-5xl px-5 pt-16 pb-32 sm:px-8">
        <div className="flex gap-4 text-sm text-neutral-500">
          <Link href="/" className="underline-offset-4 hover:underline">
            Home
          </Link>
          <Link href="/ideas" className="underline-offset-4 hover:underline">
            Ideas
          </Link>
          <Link href="/model" className="underline-offset-4 hover:underline">
            Model stats
          </Link>
        </div>
        <h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
          Landing page variations
        </h1>
        <p className="mt-3 max-w-2xl text-neutral-600">
          Three options per model, alongside the Codex concept and the current
          WordPress site. Options 1 and 2 come from the same brief; option 3
          mixes the two, set in Overpass with the live site's photography. The
          six options and the Codex concept share the same headline; what
          differs is below.
        </p>

        <div className="mt-10">
          <DesignTable
            entries={ALL}
            caption="Design traits of the six options and two reference sites"
            minWidth="1180px"
          />
        </div>

        {GROUPS.map((model) => (
          <section key={model} className="mt-14">
            <h2 className="text-2xl font-semibold tracking-tight">
              {MODELS[model].name}
            </h2>
            <div className="mt-5 space-y-6">
              {VARIATION_ENTRIES.filter((e) =>
                e.href.startsWith(`/landing/${model}/`),
              ).map((e) => (
                <DesignCard key={e.id} entry={e} />
              ))}
            </div>
          </section>
        ))}

        <section className="mt-14">
          <h2 className="text-2xl font-semibold tracking-tight">
            Reference sites
          </h2>
          <p className="mt-1 text-sm text-neutral-500">
            Not generated here; summarised from their live HTML and CSS for
            comparison.
          </p>
          <div className="mt-5 space-y-6">
            {REFERENCE_ENTRIES.map((e) => (
              <DesignCard key={e.id} entry={e} />
            ))}
          </div>
        </section>

        <section className="mt-14">
          <div className="flex flex-wrap items-baseline justify-between gap-3">
            <h2 className="text-2xl font-semibold tracking-tight">
              Reimagined sites
            </h2>
            <Link
              href="/landing/fable/reimagined"
              className="text-sm font-medium underline-offset-4 hover:underline"
            >
              Open the set
            </Link>
          </div>
          <p className="mt-1 text-sm text-neutral-500">
            Four full pages by Claude Fable 5.1. Each borrows the structure of a
            reference site and rebuilds it for coach charter and cars with
            driver, in Overpass with the teal-and-amber palette and the brand
            photography.
          </p>
          <ul className="mt-5 grid gap-4 sm:grid-cols-2">
            {REIMAGINED.map((r) => (
              <li
                key={r.slug}
                className="rounded-2xl border border-neutral-200 p-5"
              >
                <div className="flex flex-wrap items-baseline justify-between gap-3">
                  <h3 className="text-lg font-semibold">
                    {r.name} · {r.label}
                  </h3>
                  <Link
                    href={r.href}
                    className="text-sm font-medium underline-offset-4 hover:underline"
                  >
                    Open page
                  </Link>
                </div>
                <p className="mt-1 text-sm text-neutral-500">{r.source}</p>
                <p className="mt-3 mb-3 text-sm text-neutral-700">
                  {r.concept}
                </p>
                <Chips items={r.borrowed} />
              </li>
            ))}
          </ul>
        </section>

        <section className="mt-14">
          <div className="flex flex-wrap items-baseline justify-between gap-3">
            <h2 className="text-2xl font-semibold tracking-tight">Ideas</h2>
            <Link
              href="/ideas"
              className="text-sm font-medium underline-offset-4 hover:underline"
            >
              Open the set
            </Link>
          </div>
          <p className="mt-1 max-w-3xl text-sm text-neutral-500">
            Four pages by Claude Fable 5.1 that drop the platform layout instead
            of restyling it. Still a travel booking app, but the booking control
            is the page: a sentence, a headcount, a mileage chart, a day. None
            use Overpass, teal and amber, or the structure of Agoda, Airbnb or
            Booking.com.
          </p>
          <ul className="mt-5 grid gap-4 sm:grid-cols-2">
            {IDEAS.map((idea) => {
              const design = IDEA_ENTRIES.find(
                (e) => e.href === idea.href,
              )?.design;
              return (
                <li
                  key={idea.href}
                  className="rounded-2xl border border-neutral-200 p-5"
                >
                  <div className="flex flex-wrap items-baseline justify-between gap-3">
                    <h3 className="text-lg font-semibold">
                      {idea.option}. {idea.name}
                    </h3>
                    <Link
                      href={idea.href}
                      className="text-sm font-medium underline-offset-4 hover:underline"
                    >
                      Open page
                    </Link>
                  </div>
                  <p className="mt-1 text-sm text-neutral-500">
                    {idea.control}
                    {design
                      ? ` · ${design.display.family} with ${design.body.family}`
                      : ""}
                  </p>
                  {design && (
                    <div className="mt-3 flex gap-1">
                      {design.palette.map((s) => (
                        <span
                          key={s.hex}
                          title={`${s.name} ${s.hex}`}
                          className="h-5 w-8 rounded-sm ring-1 ring-black/10"
                          style={{ backgroundColor: s.hex }}
                        />
                      ))}
                    </div>
                  )}
                  <p className="mt-3 mb-3 text-sm text-neutral-700">
                    {idea.concept}
                  </p>
                  <Chips items={idea.replaces} />
                </li>
              );
            })}
          </ul>
        </section>
      </main>
    </div>
  );
}
