import type { Metadata } from "next";
import Link from "next/link";
import {
  MODELS,
  VARIATIONS,
  formatDuration,
  formatTokens,
  type Run,
} from "./_data";

export const metadata: Metadata = {
  title: "Landing page variations | Heavenly Travel",
  description:
    "Six landing page concepts for Heavenly Travel, generated by Claude Opus 5 and Claude Fable 5.1.",
};

function sum(runs: Run[], key: "tokens" | "toolCalls" | "durationMs") {
  if (runs.some((r) => r[key] == null)) return null;
  return runs.reduce((total, r) => total + (r[key] ?? 0), 0);
}

export default function LandingIndex() {
  return (
    <div className="min-h-screen bg-neutral-50 font-sans text-neutral-900">
      <main className="mx-auto max-w-6xl px-5 pt-16 pb-32">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Landing page variations
        </h1>
        <p className="mt-3 max-w-2xl text-neutral-600">
          Three concepts from each model, built from the same brief and the
          same three direction seeds. Use the floating bar at the bottom to
          switch between them.
        </p>

        <ul className="mt-12 grid gap-6 md:grid-cols-2">
          {VARIATIONS.map((v) => {
            const totalTokens = sum(v.runs, "tokens");
            const totalDuration = sum(v.runs, "durationMs");
            return (
              <li
                key={v.href}
                className="rounded-2xl border border-neutral-200 bg-white p-6"
              >
                <div className="flex items-baseline justify-between gap-4">
                  <h2 className="text-lg font-semibold">
                    <Link
                      href={v.href}
                      className="underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2"
                    >
                      {MODELS[v.model].name}, option {v.option}
                    </Link>
                  </h2>
                  <code className="text-xs text-neutral-500">{v.href}</code>
                </div>
                <p className="mt-1 text-sm text-neutral-500">
                  Seed: {v.seed}
                </p>
                <p className="mt-3 text-neutral-700">{v.concept}</p>

                <table className="mt-5 w-full text-left text-sm tabular-nums">
                  <caption className="sr-only">
                    Generation metadata for {MODELS[v.model].name}, option{" "}
                    {v.option}
                  </caption>
                  <thead className="text-neutral-500">
                    <tr className="border-b border-neutral-200">
                      <th scope="col" className="py-2 font-medium">
                        Run
                      </th>
                      <th scope="col" className="py-2 text-right font-medium">
                        Tokens
                      </th>
                      <th scope="col" className="py-2 text-right font-medium">
                        Tool calls
                      </th>
                      <th scope="col" className="py-2 text-right font-medium">
                        Time
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {v.runs.map((run) => (
                      <tr
                        key={run.label}
                        className="border-b border-neutral-100"
                      >
                        <th scope="row" className="py-2 font-normal">
                          {run.label}
                        </th>
                        <td className="py-2 text-right">
                          {formatTokens(run.tokens)}
                        </td>
                        <td className="py-2 text-right">
                          {run.toolCalls ?? "Pending"}
                        </td>
                        <td className="py-2 text-right">
                          {formatDuration(run.durationMs)}
                        </td>
                      </tr>
                    ))}
                    <tr className="font-medium">
                      <th scope="row" className="py-2">
                        Total
                      </th>
                      <td className="py-2 text-right">
                        {formatTokens(totalTokens)}
                      </td>
                      <td className="py-2 text-right">
                        {sum(v.runs, "toolCalls") ?? "Pending"}
                      </td>
                      <td className="py-2 text-right">
                        {formatDuration(totalDuration)}
                      </td>
                    </tr>
                  </tbody>
                </table>
                <p className="mt-3 text-xs text-neutral-500">
                  Model ID: {MODELS[v.model].id}
                </p>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
